#
# Base settings for Debian
#
#

- name: Update cache
  apt: update_cache=yes

- name: Upgrade distribution
  apt: upgrade=dist

- name: Install defaults packages
  apt: pkg=$item state=present
  with_items:
    - man-db
    - apt-file
    - wget
    - curl
    - ngrep
    - tree
    - bash-completion
    - language-pack-fr
    - git
    - gitk
    - unzip
    - logrotate
    - rsyslog
    - sysstat
    - tmux
    - w3m
    - libgtk2.0-0
    - libswt-gtk-3-jni
    - libswt-gtk-3-java
    - mlocate
    - genisoimage
    - dnsutils
    - vim

- name: Install Python tools
  apt: pkg=$item state=present
  with_items:
    - libcurl4-gnutls-dev
    - python-dev
    - python-pip
    - python-pycurl
    - python-netaddr
    - software-properties-common

- name: Install apt sources.list
  copy: >
    src=files/sources.list dest=/etc/apt/
    owner=root mode=644

