source 'http://rubygems.org'

ruby '2.1.1'

# Sinatra microframework
gem 'sinatra', '>= 2.0.0', require: "sinatra/base"
gem 'sinatra-contrib', '>= 2.0.0'
gem 'multi_json'

# Serve with unicorn
#gem 'unicorn'

group :development, :test do
  gem 'guard-minitest'
  gem 'rake'
end

group :test do
  gem 'rack-test', '~> 0.6.2'
  gem 'mocha', '~> 0.14.0', require: false
  gem 'simplecov'
  gem 'coveralls'
end
